<?php
	// DBP v4 book_codes are the same as the abs_codes.
	$this->book_codes_names		= array(
										'GEN' => __('Genesis', 'bible-reading-plans'),
										'EXO' => __('Exodus', 'bible-reading-plans'),
										'LEV' => __('Leviticus', 'bible-reading-plans'),
										'NUM' => __('Numbers', 'bible-reading-plans'),
										'DEU' => __('Deuteronomy', 'bible-reading-plans'),
										'JOS' => __('Joshua', 'bible-reading-plans'),
										'JDG' => __('Judges', 'bible-reading-plans'),
										'RUT' => __('Ruth', 'bible-reading-plans'),
										'1SA' => __('1 Samuel', 'bible-reading-plans'),
										'2SA' => __('2 Samuel', 'bible-reading-plans'),
										'1KI' => __('1 Kings', 'bible-reading-plans'),
										'2KI' => __('2 Kings', 'bible-reading-plans'),
										'1CH' => __('1 Chronicles', 'bible-reading-plans'),
										'2CH' => __('2 Chronicles', 'bible-reading-plans'),
										'EZR' => __('Ezra', 'bible-reading-plans'),
										'NEH' => __('Nehemiah', 'bible-reading-plans'),
										'EST' => __('Esther', 'bible-reading-plans'),
										'JOB' => __('Job', 'bible-reading-plans'),
										'PSA' => __('Psalms', 'bible-reading-plans'),
										'PRO' => __('Proverbs', 'bible-reading-plans'),
										'ECC' => __('Ecclesiastes', 'bible-reading-plans'),
										'SNG' => __('Song of Solomon', 'bible-reading-plans'),
										'ISA' => __('Isaiah', 'bible-reading-plans'),
										'JER' => __('Jeremiah', 'bible-reading-plans'),
										'LAM' => __('Lamentations', 'bible-reading-plans'),
										'EZK' => __('Ezekiel', 'bible-reading-plans'),
										'DAN' => __('Daniel', 'bible-reading-plans'),
										'HOS' => __('Hosea', 'bible-reading-plans'),
										'JOL' => __('Joel', 'bible-reading-plans'),
										'AMO' => __('Amos', 'bible-reading-plans'),
										'OBA' => __('Obadiah', 'bible-reading-plans'),
										'JON' => __('Jonah', 'bible-reading-plans'),
										'MIC' => __('Micah', 'bible-reading-plans'),
										'NAM' => __('Nahum', 'bible-reading-plans'),
										'HAB' => __('Habakkuk', 'bible-reading-plans'),
										'ZEP' => __('Zephaniah', 'bible-reading-plans'),
										'HAG' => __('Haggai', 'bible-reading-plans'),
										'ZEC' => __('Zechariah', 'bible-reading-plans'),
										'MAL' => __('Malachi', 'bible-reading-plans'),
										'1ES' => __('1 Esdras', 'bible-reading-plans'),
										'2ES' => __('2 Esdras', 'bible-reading-plans'),
										'TOB' => __('Tobit', 'bible-reading-plans'),
										'JDT' => __('Judith', 'bible-reading-plans'),
										'ESG' => __('Esther (Greek)', 'bible-reading-plans'),
										'WIS' => __('Wisdom', 'bible-reading-plans'),
										'SIR' => __('Ecclesiasticus', 'bible-reading-plans'),
										'BAR' => __('Baruch', 'bible-reading-plans'),
										'S3Y' => __('Song of the Three', 'bible-reading-plans'),
										'SUS' => __('Susanna', 'bible-reading-plans'),
										'BEL' => __('Bel and the Dragon', 'bible-reading-plans'),
										'MAN' => __('Manasseh', 'bible-reading-plans'),
										'1MA' => __('1 Maccabees', 'bible-reading-plans'),
										'2MA' => __('2 Maccabees', 'bible-reading-plans'),
										'MAT' => __('Matthew', 'bible-reading-plans'),
										'MRK' => __('Mark', 'bible-reading-plans'),
										'LUK' => __('Luke', 'bible-reading-plans'),
										'JHN' => __('John', 'bible-reading-plans'),
										'ACT' => __('Acts', 'bible-reading-plans'),
										'ROM' => __('Romans', 'bible-reading-plans'),
										'1CO' => __('1 Corinthians', 'bible-reading-plans'),
										'2CO' => __('2 Corinthians', 'bible-reading-plans'),
										'GAL' => __('Galatians', 'bible-reading-plans'),
										'EPH' => __('Ephesians', 'bible-reading-plans'),
										'PHP' => __('Philippians', 'bible-reading-plans'),
										'COL' => __('Colossians', 'bible-reading-plans'),
										'1TH' => __('1 Thessalonians', 'bible-reading-plans'),
										'2TH' => __('2 Thessalonians', 'bible-reading-plans'),
										'1TI' => __('1 Timothy', 'bible-reading-plans'),
										'2TI' => __('2 Timothy', 'bible-reading-plans'),
										'TIT' => __('Titus', 'bible-reading-plans'),
										'PHM' => __('Philemon', 'bible-reading-plans'),
										'HEB' => __('Hebrews', 'bible-reading-plans'),
										'JAS' => __('James', 'bible-reading-plans'),
										'1PE' => __('1 Peter', 'bible-reading-plans'),
										'2PE' => __('2 Peter', 'bible-reading-plans'),
										'1JN' => __('1 John', 'bible-reading-plans'),
										'2JN' => __('2 John', 'bible-reading-plans'),
										'3JN' => __('3 John', 'bible-reading-plans'),
										'JUD' => __('Jude', 'bible-reading-plans'),
										'REV' => __('Revelation', 'bible-reading-plans'),
										);
/*	$this->book_names_ap	= array(// Apocrypha
										__('1 Esdras', 'bible-reading-plans'),
										__('2 Esdras', 'bible-reading-plans'),
										__('Tobit', 'bible-reading-plans'),
										__('Judith', 'bible-reading-plans'),
										__('Esther (Greek)', 'bible-reading-plans'),
										__('Wisdom', 'bible-reading-plans'),
										__('Ecclesiasticus', 'bible-reading-plans'),
										__('Baruch', 'bible-reading-plans'),
										__('Song of the Three', 'bible-reading-plans'),
										__('Susanna', 'bible-reading-plans'),
										__('Bel and the Dragon', 'bible-reading-plans'),
										__('Manasseh', 'bible-reading-plans'),
										__('1 Maccabees', 'bible-reading-plans'),
										__('2 Maccabees', 'bible-reading-plans'),
										);*/
	$this->book_codes_ot		= array( // Old Testament
										'GEN',
										'EXO',
										'LEV',
										'NUM',
										'DEU',
										'JOS',
										'JDG',
										'RUT',
										'1SA',
										'2SA',
										'1KI',
										'2KI',
										'1CH',
										'2CH',
										'EZR',
										'NEH',
										'EST',
										'JOB',
										'PSA',
										'PRO',
										'ECC',
										'SNG',
										'ISA',
										'JER',
										'LAM',
										'EZK',
										'DAN',
										'HOS',
										'JOL',
										'AMO',
										'OBA',
										'JON',
										'MIC',
										'NAM',
										'HAB',
										'ZEP',
										'HAG',
										'ZEC',
										'MAL',
										);
	$this->book_codes_ap		= array(// Apocrypha
										'1ES',
										'2ES',
										'TOB',
										'JDT',
										'ESG',
										'WIS',
										'SIR',
										'BAR',
										'S3Y',
										'SUS',
										'BEL',
										'MAN',
										'1MA',
										'2MA',
										);
	$this->book_codes_nt		= array(// New Testament
										'MAT',
										'MRK',
										'LUK',
										'JHN',
										'ACT',
										'ROM',
										'1CO',
										'2CO',
										'GAL',
										'EPH',
										'PHP',
										'COL',
										'1TH',
										'2TH',
										'1TI',
										'2TI',
										'TIT',
										'PHM',
										'HEB',
										'JAS',
										'1PE',
										'2PE',
										'1JN',
										'2JN',
										'3JN',
										'JUD',
										'REV',
										);
	$this->bk_cds_dpp2_to_dbp4	= array('Gen'	 => 'GEN',
										'Exod'	 => 'EXO',
										'Lev'	 => 'LEV',
										'Num'	 => 'NUM',
										'Deut'	 => 'DEU',
										'Josh'	 => 'JOS',
										'Judg'	 => 'JDG',
										'Ruth'	 => 'RUT',
										'1Sam'	 => '1SA',
										'2Sam'	 => '2SA',
										'1Kgs'	 => '1KI',
										'2Kgs'	 => '2KI',
										'1Chr'	 => '1CH',
										'2Chr'	 => '2CH',
										'Ezra'	 => 'EZR',
										'Neh'	 => 'NEH',
										'Esth'	 => 'EST',
										'Job'	 => 'JOB',
										'Ps'	 => 'PSA',
										'Prov'	 => 'PRO',
										'Eccl'	 => 'ECC',
										'Song'	 => 'SNG',
										'Isa'	 => 'ISA',
										'Jer'	 => 'JER',
										'Lam'	 => 'LAM',
										'Ezek'	 => 'EZK',
										'Dan'	 => 'DAN',
										'Hos'	 => 'HOS',
										'Joel'	 => 'JOL',
										'Amos'	 => 'AMO',
										'Obad'	 => 'OBA',
										'Jonah'	 => 'JON',
										'Mic'	 => 'MIC',
										'Nah'	 => 'NAM',
										'Hab'	 => 'HAB',
										'Zeph'	 => 'ZEP',
										'Hag'	 => 'HAG',
										'Zech'	 => 'ZEC',
										'Mal'	 => 'MAL',
										'1Es'	 => '1ES',
										'2Es'	 => '2ES',
										'Tob'	 => 'TOB',
										'Jdt'	 => 'JDT',
										'EsG'	 => 'ESG',
										'Wis'	 => 'WIS',
										'Sir'	 => 'SIR',
										'Bar'	 => 'BAR',
										'S3Y'	 => 'S3Y',
										'Sus'	 => 'SUS',
										'Bel'	 => 'BEL',
										'Man'	 => 'MAN',
										'1Ma'	 => '1MA',
										'2Ma'	 => '2MA',
										'Matt'	 => 'MAT',
										'Mark'	 => 'MRK',
										'Luke'	 => 'LUK',
										'John'	 => 'JHN',
										'Acts'	 => 'ACT',
										'Rom'	 => 'ROM',
										'1Cor'	 => '1CO',
										'2Cor'	 => '2CO',
										'Gal'	 => 'GAL',
										'Eph'	 => 'EPH',
										'Phil'	 => 'PHP',
										'Col'	 => 'COL',
										'1Thess' => '1TH',
										'2Thess' => '2TH',
										'1Tim'	 => '1TI',
										'2Tim'	 => '2TI',
										'Titus'	 => 'TIT',
										'Phlm'	 => 'PHM',
										'Heb'	 => 'HEB',
										'Jas'	 => 'JAS',
										'1Pet'	 => '1PE',
										'2Pet'	 => '2PE',
										'1John'	 => '1JN',
										'2John'	 => '2JN',
										'3John'	 => '3JN',
										'Jude'	 => 'JUD',
										'Rev'	 => 'REV',
										);
?>
