<?php
	$this->holy_days		= array(
									'01-01' => __('The Circumcision and Holy Name of Our Lord Jesus Christ', 'bible-reading-plans'),
									'01-06' => __('The Epiphany of Our Lord Jesus Christ', 'bible-reading-plans'),
									'01-18' => __('Confession of Peter the Apostle', 'bible-reading-plans'),
									'01-25' => __('Conversion of Paul the Apostle', 'bible-reading-plans'),
									'02-02' => __('The Presentation of Our Lord Jesus Christ in the Temple', 'bible-reading-plans'),
									'02-24' => __('Matthias the Apostle', 'bible-reading-plans'),
									'03-25' => __('The Annunciation of Our Lord Jesus Christ to the Virgin Mary', 'bible-reading-plans'),
									'04-25' => __('Mark the Evangelist', 'bible-reading-plans'),
									'05-01' => __('Philip and James, Apostles', 'bible-reading-plans'),
									'05-31' => __('The Visitation of the Virgin Mary to Elizabeth and Zechariah', 'bible-reading-plans'),
									'06-11' => __('Barnabas the Apostle', 'bible-reading-plans'),
									'06-24' => __('The Nativity of John the Baptist', 'bible-reading-plans'),
									'06-29' => __('Peter and Paul, Apostles', 'bible-reading-plans'),
									'07-22' => __('Mary Magdalene', 'bible-reading-plans'),
									'07-25' => __('James the Elder, Apostle', 'bible-reading-plans'),
									'08-06' => __('The Transfiguration of Our Lord Jesus Christ', 'bible-reading-plans'),
									'08-15' => __('The Virgin Mary, Mother of Our Lord Jesus Christ', 'bible-reading-plans'),
									'08-24' => __('Bartholomew the Apostle', 'bible-reading-plans'),
									'09-14' => __('Holy Cross Day', 'bible-reading-plans'),
									'09-21' => __('Matthew, Apostle and Evangelist', 'bible-reading-plans'),
									'09-29' => __('Holy Michael and All Angels', 'bible-reading-plans'),
									'10-18' => __('Luke the Evangelist and Companion of Paul', 'bible-reading-plans'),
									'10-23' => __('James of Jerusalem, Bishop and Martyr, Brother of Our Lord', 'bible-reading-plans'),
									'10-28' => __('Simon and Jude, Apostles', 'bible-reading-plans'),
									'11-01' => __('All Saints\' Day', 'bible-reading-plans'),
									'11-30' => __('Andrew the Apostle', 'bible-reading-plans'),
									'12-21' => __('Thomas the Apostle', 'bible-reading-plans'),
									'12-25' => __('Christmas Day', 'bible-reading-plans'),
									'12-26' => __('Stephen, Deacon and Martyr', 'bible-reading-plans'),
									'12-27' => __('John, Apostle and Evangelist', 'bible-reading-plans'),
									'12-28' => __('The Holy Innocents', 'bible-reading-plans'),
									);
	$this->moveable_feasts	= array(
									__('Ash Wednesday', 'bible-reading-plans'),
									__('Maundy Thursday', 'bible-reading-plans'),
									__('Good Friday', 'bible-reading-plans'),
									__('Holy Saturday', 'bible-reading-plans'),
									__('Easter Sunday', 'bible-reading-plans'),
									__('Ascension Day', 'bible-reading-plans'),
									__('Pentecost', 'bible-reading-plans'),
									);
?>
