<?php
	$this->poetic = array(
						'Job'				=> 'all', 
						'Psalms'			=> 'all', 
						'Proverbs'			=> 'all', 
						'Psalm'				=> 'all', 
						'Proverb'			=> 'all', 
						'Ecclesiastes'		=> 'all', 
						'Song of Solomon'	=> 'all',
						'Joel'				=> 'all',
						'Amos'				=> 'all',
						'Obadiah'			=> 'all',
						/* 
						// Some of the other poetic passages, for which the code has not yet been created.
						'2 Samuel'	=> array('22'	=> '2-51'),
						'2 Kings'	=> array('19'	=> '21b-28'),
						'Jeremiah'	=> array('13'	=> '15-27'),
						'Jeremiah'	=> array('12'	=> '1-13'),
						'Jeremiah'	=> array('23'	=> '9-15'),
						'Jeremiah'	=> array('23'	=> '18-22'),
						'Jeremiah'	=> array('25'	=> '30-38'),
						'Acts'		=> array('1'	=> '20'),
						'Acts'		=> array('2'	=> '16-21'),
						'Acts'		=> array('2'	=> '25-28'),
						'Acts'		=> array('2'	=> '34-35'),
						'Acts'		=> array('4'	=> '25b-26'),
						'Acts'		=> array('7'	=> '42b-43'),
						'Acts'		=> array('7'	=> '49-50'),
						'Acts'		=> array('13'	=> '33b'),
						'Acts'		=> array('13'	=> '34b'),
						'Acts'		=> array('13'	=> '35b'),
						'Acts'		=> array('13'	=> '41'),
						'Acts'		=> array('15'	=> '16-17'),
						'Acts'		=> array('17'	=> '28'),
						'Ephesians'	=> array('5'	=> '14b'),
						'Hebrews'	=> array('1'	=> '5-14'),
						'Hebrews'	=> array('2'	=> '5-8a'),
						'Hebrews'	=> array('2'	=> '12b-13'),
						'Hebrews'	=> array('3'	=> '7-11'),
						'Hebrews'	=> array('3'	=> '15b'),
						'Hebrews'	=> array('4'	=> '3b'),
						'Hebrews'	=> array('4'	=> '5b'), 
						'Hebrews'	=> array('4'	=> '7b'), 
						'Hebrews'	=> array('5'	=> '5-6'),
						'Hebrews'	=> array('7'	=> '17b'),
						'Hebrews'	=> array('7'	=> '21b'),
						'Hebrews'	=> array('8'	=> '8b-12'),
						'Hebrews'	=> array('10'	=> '5b-7'),
						'Hebrews'	=> array('10'	=> '16-17'),
						'Hebrews'	=> array('10'	=> '37b-38'),
						'Hebrews'	=> array('13'	=> '6b'),
						'1 Peter'	=> array('3'	=> '10-12'),
						'1 Peter'	=> array('4'	=> '18'),
						''	=> array(''	=> ''),
						*/
						);
?>
